### PR TITLE
Removed unused variable (+ new release request)

### PR DESCRIPTION
**Pull request by mdevaev**
The compiler issues a warning on this, which makes my eyelid twitch a little :)

Also could you make a new release + tag?

### CODE REVIEW

**Comment by Harvie** [comment]
Perhaps you can increase version to 0.0.4 in library.properties before i merge

**Comment by mdevaev** [comment]
Done

**Comment by mdevaev** [comment]
Boop

**Comment by Harvie** [comment]
Thanks

**Pull request merged**
